"""Uppdate role

Revision ID: f1e5267310f2
Revises: 066cc446fa12
Create Date: 2025-02-14 16:46:10.384793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f1e5267310f2'
down_revision: Union[str, None] = '066cc446fa12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Оновлюємо колонку "role" в таблиці "users"
    op.execute("""
    CREATE TYPE roleenum AS ENUM ('admin', 'user');
    """)

    # Оновлюємо колонку "role" в таблиці "users" з явним перетворенням
    op.alter_column('users', 'role',
                    type_=postgresql.ENUM('admin', 'user', name='roleenum'),
                    existing_type=sa.String(),
                    postgresql_using="role::roleenum")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TYPE roleenum;")
    op.alter_column('users', 'role', type_=sa.String())
    # ### end Alembic commands ###
