"""delete demenitions

Revision ID: 0adbe4aa841e
Revises: e4d30526b72c
Create Date: 2025-02-17 11:17:35.646265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0adbe4aa841e'
down_revision: Union[str, None] = 'e4d30526b72c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shipments', 'dimensions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shipments', sa.Column('dimensions', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
