"""change route and add RouteShipments

Revision ID: 302559c07f0a
Revises: 184ee3b2acc5
Create Date: 2025-02-18 12:50:22.737950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '302559c07f0a'
down_revision: Union[str, None] = '184ee3b2acc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('route_shipments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_route_shipments_id'), 'route_shipments', ['id'], unique=False)
    op.add_column('routes', sa.Column('branch_from_id', sa.Integer(), nullable=False))
    op.add_column('routes', sa.Column('branch_to_id', sa.Integer(), nullable=False))
    op.add_column('routes', sa.Column('courier_id', sa.Integer(), nullable=True))
    op.alter_column('routes', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint('routes_branch_from_fkey', 'routes', type_='foreignkey')
    op.drop_constraint('routes_branch_to_fkey', 'routes', type_='foreignkey')
    op.create_foreign_key(None, 'routes', 'branches', ['branch_to_id'], ['id'])
    op.create_foreign_key(None, 'routes', 'users', ['courier_id'], ['id'])
    op.create_foreign_key(None, 'routes', 'branches', ['branch_from_id'], ['id'])
    op.drop_column('routes', 'estimated_time')
    op.drop_column('routes', 'branch_to')
    op.drop_column('routes', 'branch_from')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routes', sa.Column('branch_from', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('routes', sa.Column('branch_to', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('routes', sa.Column('estimated_time', postgresql.INTERVAL(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'routes', type_='foreignkey')
    op.drop_constraint(None, 'routes', type_='foreignkey')
    op.drop_constraint(None, 'routes', type_='foreignkey')
    op.create_foreign_key('routes_branch_to_fkey', 'routes', 'branches', ['branch_to'], ['id'])
    op.create_foreign_key('routes_branch_from_fkey', 'routes', 'branches', ['branch_from'], ['id'])
    op.alter_column('routes', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('routes', 'courier_id')
    op.drop_column('routes', 'branch_to_id')
    op.drop_column('routes', 'branch_from_id')
    op.drop_index(op.f('ix_route_shipments_id'), table_name='route_shipments')
    op.drop_table('route_shipments')
    # ### end Alembic commands ###
