"""added barcode_path to users

Revision ID: 5cdc923aed68
Revises: b0bdb64f587f
Create Date: 2025-02-19 13:45:12.191452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cdc923aed68'
down_revision: Union[str, None] = 'b0bdb64f587f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('barcode_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'barcode_path')
    # ### end Alembic commands ###
