"""change fk Route.courier_id > Courier.id

Revision ID: 64325f20cfe5
Revises: c90cc88ebee8
Create Date: 2025-02-18 15:08:06.032885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64325f20cfe5'
down_revision: Union[str, None] = 'c90cc88ebee8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('routes_courier_id_fkey', 'routes', type_='foreignkey')
    op.create_foreign_key(None, 'routes', 'couriers', ['courier_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'routes', type_='foreignkey')
    op.create_foreign_key('routes_courier_id_fkey', 'routes', 'users', ['courier_id'], ['id'])
    # ### end Alembic commands ###
