"""added barcode_id to users

Revision ID: b0bdb64f587f
Revises: f2af37a36305
Create Date: 2025-02-19 13:23:49.488420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0bdb64f587f'
down_revision: Union[str, None] = 'f2af37a36305'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('barcode_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'barcode_id')
    # ### end Alembic commands ###
