"""added barcode_path to shipment

Revision ID: bf0c86ab4c54
Revises: 5cdc923aed68
Create Date: 2025-02-19 13:54:13.434922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf0c86ab4c54'
down_revision: Union[str, None] = '5cdc923aed68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shipments', sa.Column('barcode_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shipments', 'barcode_path')
    # ### end Alembic commands ###
