"""added location to courier

Revision ID: fee53fd1195a
Revises: 0adbe4aa841e
Create Date: 2025-02-17 14:17:43.770910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fee53fd1195a'
down_revision: Union[str, None] = '0adbe4aa841e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('couriers', sa.Column('locate', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('couriers', 'locate')
    # ### end Alembic commands ###
